on:
  pull_request_target:
    types:
      - closed
  pull_request:
    branches:
      - 'dev'
jobs:
  dev_branches:
      if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      env:
        DOCKER_TAG:
      steps:
       - name: Extract branch name
         shell: bash
         run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
         id: extract_branch
       - name: BTC (build to cache)
         uses: docker/setup-buildx-action@v1
       - name: Login to Docker Hub
         uses: docker/login-action@v1
         with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
       - name: Set dynamic branch Docker tag
         id: set_docker_tag
         run: echo "DOCKER_TAG=marceliux/jardinbinario:dev/${{ steps.extract_branch.outputs.branch }}" >> $GITHUB_ENV
       - name: Build dev branch tag and push to Docker Hub
         uses: docker/build-push-action@v3
         with:
          push: true
          tags: ${{ env.DOCKER_TAG }}
          build-args: |
              "NEXT_PUBLIC_BACKEND_URL=${{ secrets.NEXT_PUBLIC_BACKEND_URL }}"
              "NEXT_PUBLIC_PLACEHOLDER_IMAGE=${{ secrets.NEXT_PUBLIC_PLACEHOLDER_IMAGE }}"
              "NEXT_PUBLIC_UPLOAD_IMAGE=${{ secrets.NEXT_PUBLIC_UPLOAD_IMAGE }}"
              "NEXT_PUBLIC_CLOUDINARY_UPLOAD_URL=${{ secrets.NEXT_PUBLIC_CLOUDINARY_UPLOAD_URL }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max